# Generated by Django 4.2.16 on 2026-06-13 21:31

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_tenant'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.TenantAwareUserManager()),
            ],
        ),
    ]
