# Generated by Django 5.0.14 on 2026-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_tenant_invoiceline_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_ice',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_identifiant_fiscal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_registre_commerce',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_taxe_professionnelle',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
