# Generated by Django 5.0.14 on 2026-07-25 22:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_customer_ice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(default='30 jours', help_text="Payment terms, e.g. '30 jours', 'À réception'", max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_exempt_notice',
            field=models.CharField(blank=True, help_text='Auto-populated for auto_entrepreneur or export regimes', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Default VAT rate applied to invoice (can be overridden per line)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='VAT rate for this line, e.g. 0.20 for 20%%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Alias for total_ttc', max_digits=14),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
