# Generated by Django 5.0.14 on 2026-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Built for Moroccan compliance', max_length=255)),
                ('law_title', models.CharField(default='Law 09-08 (CNDP)', max_length=255)),
                ('items', models.TextField(help_text='One compliance item per line')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compliance Section',
                'db_table': 'landing_compliance',
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Ready to move beyond spreadsheets?', max_length=255)),
                ('subtitle', models.CharField(default='Join Moroccan logistics teams that trust Veloxa.', max_length=255)),
                ('button_text', models.CharField(default='Get early access', max_length=100)),
                ('placeholder', models.CharField(default='Enter your work email', max_length=255)),
                ('footnote', models.CharField(default='No credit card required. 14-day free trial.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'db_table': 'landing_cta',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_bg', models.CharField(default='#2563eb', help_text='CSS gradient start', max_length=7)),
                ('icon_bg_end', models.CharField(default='#1d4ed8', help_text='CSS gradient end', max_length=7)),
                ('icon_class', models.CharField(default='fas fa-book', help_text='FontAwesome icon class', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'db_table': 'landing_feature',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Inventory you can trust. Stock you can verify.', max_length=255)),
                ('subtitle', models.TextField(default='Immutable ledger, automated back-orders, and full audit trails...')),
                ('cta_text', models.CharField(default='Start free trial', max_length=100)),
                ('cta_link', models.CharField(default='#contact', max_length=255)),
                ('secondary_cta_text', models.CharField(default='Read the architecture', max_length=100)),
                ('secondary_cta_link', models.CharField(default='#architecture', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'db_table': 'landing_hero',
            },
        ),
        migrations.CreateModel(
            name='LandingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Landing Lead',
                'db_table': 'landing_lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(help_text="e.g. MAD 2,500 or 'Custom'", max_length=100)),
                ('period', models.CharField(help_text="e.g. 'Up to 5 users · 10k movements/mo'", max_length=200)),
                ('features', models.TextField(help_text='One feature per line')),
                ('is_popular', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, default='Most popular', max_length=100)),
                ('button_text', models.CharField(default='Request demo', max_length=100)),
                ('button_class', models.CharField(default='btn-outline', help_text='btn-primary, btn-outline, etc.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'db_table': 'landing_pricing_plan',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='HTML content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Page',
                'verbose_name_plural': 'Site Pages',
                'db_table': 'landing_site_page',
            },
        ),
        migrations.CreateModel(
            name='TrustCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_bg', models.CharField(default='linear-gradient(135deg,#2563eb,#1d4ed8)', max_length=100)),
                ('icon_class', models.CharField(default='fas fa-shield-alt', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Card',
                'db_table': 'landing_trust_card',
                'ordering': ['order'],
            },
        ),
    ]
