# Generated by Django 5.0.14 on 2026-06-12 20:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Page content with rich text editor'),
        ),
    ]
