# Generated by Django 5.0.14 on 2026-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_assign_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, help_text='Registered office address (Siège Social)', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='capital_social',
            field=models.CharField(blank=True, help_text='Share capital in MAD, e.g. 10,000.00 DH', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ice',
            field=models.CharField(blank=True, help_text='ICE — 15-digit national company identifier', max_length=15),
        ),
        migrations.AddField(
            model_name='tenant',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, help_text='IF — 8-digit Tax Identifier', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Full legal name & form, e.g. Veloxa SARL', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registre_commerce',
            field=models.CharField(blank=True, help_text='RC number + city, e.g. RC 123456 Marrakech', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='rib',
            field=models.CharField(blank=True, help_text='24-digit RIB for bank transfers', max_length=24),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_regime',
            field=models.CharField(choices=[('standard', 'Régime réel'), ('auto_entrepreneur', 'Auto-Entrepreneur'), ('export', 'Export (0% TVA)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='taxe_professionnelle',
            field=models.CharField(blank=True, help_text='TP registration number', max_length=64),
        ),
    ]
