# Generated by Django 5.0.14 on 2026-07-23 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_assign_default_tenant'),
        ('warehouse', '0003_alter_location_options_category_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('order_ref', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-release after this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='warehouse.product')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'db_table': 'warehouse_stockreservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='warehouse_s_product_a90ed1_idx'), models.Index(fields=['order_ref', 'status'], name='warehouse_s_order_r_bdaf10_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(check=models.Q(('qty__gt', 0)), name='reservation_qty_positive'),
        ),
    ]
