# Generated by Django 4.2.16 on 2026-06-12 18:24

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_customer',
                'ordering': ['-created_at'],
            },
        ),
    ]
