# Generated by Django 5.0.14 on 2026-06-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_tenant'),
        ('tenants', '0002_assign_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, help_text="ICE (Identifiant Commun de l'Entreprise) for accounting purposes", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'name'], name='crm_custome_tenant__98841d_idx'),
        ),
    ]
