# Generated by Django 5.0.14 on 2026-06-13 22:41

from django.db import migrations, models


def clear_encrypted_data(apps, schema_editor):
    Customer = apps.get_model("crm", "Customer")
    Customer.objects.update(phone="", address="")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_make_tenant_required'),
    ]

    operations = [
        migrations.RunPython(clear_encrypted_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
