# Generated by Django 5.0.14 on 2026-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_address_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tax_id',
            new_name='ice',
        ),
        migrations.AlterField(
            model_name='customer',
            name='ice',
            field=models.CharField(blank=True, help_text="ICE (Identifiant Commun de l'Entreprise) — exactly 15 digits", max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, help_text='IF (Identifiant Fiscal) for tax reporting', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='registre_commerce',
            field=models.CharField(blank=True, help_text='RC (Registre de Commerce) for legal entity verification', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='taxe_professionnelle',
            field=models.CharField(blank=True, help_text='TP (Taxe Professionnelle) for commercial documentation', max_length=30),
        ),
    ]
